### ISSUE TITLE
#parsing failed error

### ISSUE THREAD

**Issue by ayaadel9190** [MarcLavielle/mlxR#19]
i was using monolix suite 2018R2 and it was working fine
then i tired to install Rsmlx last day
and since then my monolix verson cant run new project anymore
and keep on giving me this error
#parsing failed at line 4, column 44, due to incomplete match.
#no project loaded

**Comment by ayaadel9190** [comment]
The following errors occurs when creating project:
Parsing failed at line 4, column 44, due to incomplete match.

this message keeps poping in every MonolixSuit

**Comment by MarcLavielle** [comment]
Please, write to support@lixoft.com
Thank you

Le sam. 15 sept. 2018 à 18:45, ayaadel9190 <notifications@github.com> a
écrit :

**Comment by ayaadel9190** [comment]
thank u so much
