### ISSUE TITLE
unable to install R package lixoftConnectors

### ISSUE THREAD

**Issue by YYGarden** [MarcLavielle/mlxR#26]
I already have R(3.5.3), RStudio(1.2.1335), and Monolix (2019R1) installed.
The following appeared when I tried to install lixoftConnectors:

ERROR: dependency 'RJSONIO' is not available for package 'lixoftConnectors'
* removing 'C:/Users/jiaoyy/Documents/R/win-library/3.5/lixoftConnectors'
In R CMD INSTALL
Warning in install.packages :  installation of package ‘C:/ProgramData/Lixoft/MonolixSuite2019R1/connectors/lixoftConnectors.tar.gz’ had non-zero exit status

Could you please help me with it? Thank you.

**Comment by MarcLavielle** [comment]
Hi

Please contact the Lixoft support
Marc

**Comment by YYGarden** [comment]
Thank you Marc, I has been resolved.
It requires pre-installation of 'RJSONIO'.
