### ISSUE TITLE
Error in Simulx:  build model (rethrow)

### ISSUE THREAD

**Issue by ddmarathe** [MarcLavielle/mlxR#6]
Hello Marc,
After installation of simulator and mlxR files and running an example, I am getting the following error:
------
Error in simulxunit(model = model, group = group, treatment = treatment,  : 
  build module (rethrow) :Cannot load library: C:\Users\MARATHED\lixoft\mlxlibrary\mlxlibrary110\modules\89e10a8f-d538-4f7a-b3eb-f049a029c7b9\15abea6b21524e1a87247ab74fabd4af\lib\libC15abea6b21524e1a87247ab74fabd4afPlugin.dll
In addition: Warning message:
package ‘Rcpp’ was built under R version 3.1.3 
-----
Also I see that the mlxR package is automatically stored in the following location after installing from package. C:\Users\MARATHED\Documents\R\win-library\3.1
Do I have to import the contents of mlxR to where the mlxlibrary folder is located?
Thanks for your help.
Regards,
-D. Marathe

**Comment by MarcLavielle** [comment]
dear D. Marathe,

No, you don't need to move mlxR to any other place.
but you should install mlxLibrary 1.1.1 from Lixoft website

do you have any error message when you use mlxR from CRAN?

Marc



2015-05-07 19:36 GMT+02:00 ddmarathe <notifications@github.com>:

> Hello Marc,
> After installation of simulator and mlxR files and running an example, I
> am getting the following error:
>
> Error in simulxunit(model = model, group = group, treatment = treatment, :
> build module (rethrow) :Cannot load library:
> C:\Users\MARATHED\lixoft\mlxlibrary\mlxlibrary110\modules\89e10a8f-d538-4f7a-b3eb-f049a029c7b9\15abea6b21524e1a87247ab74fabd4af\lib\libC15abea6b21524e1a87247ab74fabd4afPlugin.dll
> In addition: Warning message:
> package 'Rcpp' was built under R version 3.1.3
>
> Also I see that the mlxR package is automatically stored in the following
> location after installing from package.
> C:\Users\MARATHED\Documents\R\win-library\3.1
> Do I have to import the contents of mlxR to where the mlxlibrary folder is
> located?
> Thanks for your help.
> Regards,
> -D. Marathe
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/MarcLavielle/mlxR/issues/6>.
>



-- 

Mixed Effects Models for the Population Approach
<http://www.math.u-psud.fr/~lavielle/book.html>

*Marc Lavielle*
*Inria Saclay*

Tel: (33) 1 69 15 57 43
       (33) 6 37 31 93 05

Marc.Lavielle@inria.fr
http://www.math.u-psud.fr/~lavielle

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""

**Comment by ddmarathe** [comment]
Dear Marc,
I did download and install Simulator from Lixoft website (SimulatorInstall-V111-win64.exe). After that I downloaded mlxR from CRAN once and from Github the next time for testing whether the simulator would work. I did not get any error while loading mlxR from CRAN or from Github, but the simulator throws the above error message. I did notice that I can't find the initinitMlxLibrary.R anywhere in any of my directories or the whole harddrive. Where is the location of this file typically?

**Comment by ddmarathe** [comment]
* initMlxLibrary.R
sorry for the typo.

**Comment by MarcLavielle** [comment]
can you please

1)  install mlxR from CRAN

>install.packages("mlxR")

2) install mlxLibrary from Lixoft website

http://download.lixoft.com/?software=mlxlibrary


3)  run any of the examples

thank you

Marc


2015-05-07 21:20 GMT+02:00 ddmarathe <notifications@github.com>:

**Comment by ddmarathe** [comment]
I followed the procedure. Here is the output that I get (my version of R is v3.1.2):

> install.packages("mlxR")
Installing package into ‘C:/Users/MARATHED/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
trying URL 'http://watson.nci.nih.gov/cran_mirror/bin/windows/contrib/3.1/mlxR_2.1.1.zip'
Content type 'application/zip' length 65420 bytes (63 Kb)
opened URL
downloaded 63 Kb

package ‘mlxR’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\MARATHED\AppData\Local\Temp\3\RtmpyeDTny\downloaded_packages
> library("mlxR")
Loading required package: ggplot2
Warning messages:
1: package ‘mlxR’ was built under R version 3.1.3 
2: package ‘ggplot2’ was built under R version 3.1.3 
> setwd("M:\\Data\\Training\\Monolix_Simulations\\caseStudies\\cts")
> library(gridExtra)
Loading required package: grid
Warning message:
package ‘gridExtra’ was built under R version 3.1.3 
> source('titration.R')
> 
> adm <- list(time=seq(0,to=440,by=12), amount=20)
> 
> ppk <- c(ka_pop=0.4,   V_pop=10,    k_pop=0.05,
+          omega_ka=0.3, omega_V=0.5, omega_k=0.1, a1=0.05)
> 
> g   <- list(size=20, level='individual')
> 
> Cc  <- list(name='Cc', time=seq(0,to=440,by=1))
> y1  <- list(name='y1', time=seq(4,to=440,by=24))
> 
> s   <- list(seed=1234)
> 
> res1 <- simulx(model     = "model/cts1a.txt",
+                parameter = ppk,
+                treatment = adm,
+                group     = g,
+                output    = list(Cc, y1),
+                settings  = s)
Error in simulx(model = "model/cts1a.txt", parameter = ppk, treatment = adm,  : 
  build module (rethrow) :Cannot load library: C:\Users\MARATHED\lixoft\mlxlibrary\mlxlibrary110\modules\2004b3a4-1cc9-45c5-bd3b-b6f0856fad43\7fc832f7d8514b349c1f0eada9461772\lib\libC7fc832f7d8514b349c1f0eada9461772Plugin.dll
>

**Comment by MarcLavielle** [comment]
did you install mlxLibrary 1.1.1?

it should be installed in C:/ProgramData/Lixoft


do you have this file:
C:\Users\MARATHED\lixoft\lixoft.ini

can you copy paste its content please?


2015-05-07 21:51 GMT+02:00 ddmarathe <notifications@github.com>:

**Comment by ddmarathe** [comment]
i did install mlxlibrary 1.1.1.
Previously I had installed it in default location C:\ProgramData\Lixoft. However I was getting same error message as above. So I had uninstalled it and changed the location of next install to be C:\Users\MARATHED\MlxLibrary1.1.1

Here are the contents of C:\Users\MARATHED\lixoft\lixoft.ini :

[General]
Comment=DO NOT MODIFY - Addresses of Lixoft softwares

[softwares]
monolix=C:\\ProgramData\\Monolix\\Monolix432s\\bin\\Monolix_mcr\\runtime
mlxeditor=C:\\ProgramData\\Monolix\\Monolix432s\\bin\\Monolix_mcr\\runtime\\
perlscriptmlx=C:\\ProgramData\\Monolix\\Monolix432s\\bin\\Monolix_mcr\\runtime\\
mlxplore=C:\\Program Files\\MlxPlore\\mlxplore111\\
mlxlibrary=C:/Users/MARATHED/MlxLibrary1.1.1

**Comment by MarcLavielle** [comment]
can you please uninstall MlxLibrary from C:/Users/MARATHED/MlxLibrary1.1.1
and install it again in the default folder C:\Users\MARATHED\MlxLibrary1.1.1


2015-05-07 22:08 GMT+02:00 ddmarathe <notifications@github.com>:

**Comment by ddmarathe** [comment]
Hello Marc,
I will try to reset the default location tomorrow with our IT staff, since I do not have the admin access to do the installations. In the mean time, my hunch is that I do not have all the files from mlxR package when I install from CRAN. Under my directory of  C:\Users\MARATHED\Documents\R\win-library\3.1\mlxR\R, I see only 3 files, namely, mlxR, mlxR.rdb and mlxR.rdx. But I see on the internet that there are multiple files e.g. inlineModel.R, simulx.R, initMlxLibrary.R  etc that should be present in this package (http://rpackages.ianhowson.com/cran/mlxR/). Could you please confirm that I should have these files (or not) under the installed mlxR package?

**Comment by ddmarathe** [comment]
Ok, I uninstalled both mlxplore and mlxlibrary and reinstalled mlxplore and then mlxlibrary 1.1.1 in their default locations, then installed mlxR package from CRAN and then ran one of the example (cts1.R) that was provided under mlxR210_examples.zip in the Rstudio. Still I get the same error of build module (rethrow).
Here is the code and output:

> setwd("M:\\Data\\Training\\Monolix_Simulations\\caseStudies\\cts")
> library(gridExtra)
Loading required package: grid
Warning message:
package ‘gridExtra’ was built under R version 3.1.3 
> source('titration.R')
> adm <- list(time=seq(0,to=440,by=12), amount=20)
> 
> ppk <- c(ka_pop=0.4,   V_pop=10,    k_pop=0.05,
+          omega_ka=0.3, omega_V=0.5, omega_k=0.1, a1=0.05)
> 
> g   <- list(size=20, level='individual')
> 
> Cc  <- list(name='Cc', time=seq(0,to=440,by=1))
> y1  <- list(name='y1', time=seq(4,to=440,by=24))
> 
> s   <- list(seed=1234)
> 
> res1 <- simulx(model     = "model/cts1a.txt",
+                parameter = ppk,
+                treatment = adm,
+                group     = g,
+                output    = list(Cc, y1),
+                settings  = s)
Error in simulx(model = "model/cts1a.txt", parameter = ppk, treatment = adm,  : 
  build module (rethrow) :Cannot load library: C:\Users\MARATHED\lixoft\mlxlibrary\mlxlibrary110\modules\216d4b96-0a11-46ef-8525-85476c79468c\bd2cd098d5c44abd96401d0e6cb7a616\lib\libCbd2cd098d5c44abd96401d0e6cb7a616Plugin.dll
----------
Here is the content in the lixoft.ini file:
[General]
Comment=DO NOT MODIFY - Addresses of Lixoft softwares

[softwares]
datxplore=C:\\Program Files\\DatXPlore\\DatXPlore101\\
mlxplore=C:\\Program Files\\MlxPlore\\mlxplore111\\
mlxlibrary=C:/ProgramData/Lixoft/MlxLibrary1.1.1
------------
I do not know how to troubleshoot next. Thanks.

**Comment by RaphaelKuate** [comment]
dear D. Marathe, 
can you send me the results of the following R command Sys.getenv("HOME"), just after the error. 
Could you check if the file not being loaded (C:\Users\MARATHED\lixoft\mlxlibrary\mlxlibrary110\modules\216d4b96-0a11-46ef-8525-85476c79468c\bd2cd098d5c44abd96401d0e6cb7a616\lib\libCbd2cd098d5c44abd96401d0e6cb7a616Plugin.dll) exists, and could you also send me the result of the following command 
dir "C:\Users\MARATHED\MlxLibrary1.1.1\tools\MinGW\bin" on a windows console ? 
Sincerely, 
Raphaël. 

----- Mail original -----

**Comment by ddmarathe** [comment]
Here you go: 

> Sys.getenv("HOME")
[1] "C:/Users/MARATHED/Documents"
> Sys.getenv("LIXOFT_HOME")
[1] "C:\\ProgramData\\Lixoft\\MlxLibrary1.1.1"

I also changed LIXOFT_HOME path variable to dir where lixoft.ini is located in the next run, but the same error persisted..
> Sys.setenv("LIXOFT_HOME" = "C:\\Users\\MARATHED\\lixoft")
> Sys.getenv("LIXOFT_HOME")
[1] "C:\\Users\\MARATHED\\lixoft"

The .dll file in the error indeed exists at the location specified at the above path in the error.

The MlxLibrary1.1.1 folder is not created at C:\Users\MARATHED\.. location. During installation of mlxlibrary simulator, the default location of creation of MlxLibrary1.1.1 folder is in C:\ProgramData\Lixoft\... 

In windows console following command 
dir "C:\ProgramData\Lixoft\MlxLibrary1.1.1\tools\MinGW\bin"  
I get following output:

C:\Users\MARATHED>dir "C:\ProgramData\Lixoft\MlxLibrary1.1.1\tools\MinGW\bin"
 Volume in drive C is FDA
 Volume Serial Number is XXXX-XXXX (I am redacting the serial number)

 Directory of C:\ProgramData\Lixoft\MlxLibrary1.1.1\tools\MinGW\bin

03/16/2015  04:59 PM    <DIR>          .
03/16/2015  04:59 PM    <DIR>          ..
05/31/2013  10:33 PM           871,424 addr2line.exe
05/31/2013  10:33 PM           896,000 ar.exe
05/31/2013  10:33 PM         1,379,840 as.exe
05/31/2013  11:31 PM         1,701,888 c++.exe
05/31/2013  10:33 PM           869,888 c++filt.exe
05/31/2013  11:31 PM         1,700,352 cpp.exe
05/31/2013  10:33 PM           929,792 dlltool.exe
05/31/2013  10:33 PM            74,240 dllwrap.exe
05/31/2013  10:33 PM            59,904 elfedit.exe
05/31/2013  11:31 PM         1,701,888 g++.exe
05/31/2013  11:31 PM            56,832 gcc-ar.exe
05/31/2013  11:32 PM            56,832 gcc-nm.exe
05/31/2013  11:32 PM            56,832 gcc-ranlib.exe
05/31/2013  11:31 PM         1,699,328 gcc.exe
05/31/2013  11:32 PM         1,229,312 gcov.exe
06/01/2013  12:18 AM            77,911 gdb.exe
06/01/2013  12:18 AM         6,618,206 gdborig.exe
06/01/2013  12:18 AM           316,340 gdbserver.exe
05/31/2013  11:33 PM            76,288 gendef.exe
05/31/2013  11:34 PM            93,696 genidl.exe
05/31/2013  11:34 PM            50,688 genpeimg.exe
05/31/2013  11:31 PM         1,701,888 gfortran.exe
05/31/2013  10:33 PM           933,376 gprof.exe
05/31/2013  10:33 PM         1,239,040 ld.bfd.exe
05/31/2013  10:33 PM         1,239,040 ld.exe
05/31/2013  11:31 PM           488,166 libgcc_s_seh-1.dll
05/31/2013  11:31 PM         1,246,463 libgfortran-3.dll
05/31/2013  11:31 PM            79,449 libgomp-1.dll
05/31/2013  11:31 PM           351,039 libquadmath-0.dll
05/31/2013  11:31 PM            41,959 libssp-0.dll
05/31/2013  11:32 PM           965,582 libstdc++-6.dll
05/31/2013  10:21 PM            79,125 libwinpthread-1.dll
07/11/2009  03:34 PM           155,648 mingw32-make.exe
07/11/2009  03:34 PM           734,024 msys-1.0.dll
05/31/2013  10:33 PM           881,152 nm.exe
05/31/2013  10:33 PM         1,039,360 objcopy.exe
05/31/2013  10:33 PM         1,693,696 objdump.exe
05/31/2013  10:33 PM           896,000 ranlib.exe
05/31/2013  10:33 PM           423,936 readelf.exe
05/31/2013  10:33 PM           872,960 size.exe
05/31/2013  10:33 PM           871,936 strings.exe
05/31/2013  10:33 PM         1,039,360 strip.exe
05/31/2013  10:33 PM           894,976 windmc.exe
05/31/2013  10:33 PM           981,504 windres.exe
05/31/2013  11:31 PM         1,701,888 x86_64-w64-mingw32-c++.exe
05/31/2013  11:31 PM         1,701,888 x86_64-w64-mingw32-g++.exe
05/31/2013  11:31 PM         1,699,328 x86_64-w64-mingw32-gcc-4.8.1.exe
05/31/2013  11:31 PM            56,832 x86_64-w64-mingw32-gcc-ar.exe
05/31/2013  11:32 PM            56,832 x86_64-w64-mingw32-gcc-nm.exe
05/31/2013  11:32 PM            56,832 x86_64-w64-mingw32-gcc-ranlib.exe
05/31/2013  11:31 PM         1,699,328 x86_64-w64-mingw32-gcc.exe
05/31/2013  11:31 PM         1,701,888 x86_64-w64-mingw32-gfortran.exe
05/31/2013  11:35 PM           431,104 x86_64-w64-mingw32-widl.exe
              53 File(s)     48,473,080 bytes
               2 Dir(s)  214,767,104,000 bytes free

C:\Users\MARATHED>

**Comment by RaphaelKuate** [comment]
Please, do not change the variable LIXOFT_HOME, it must point at the location of MlxLibrary installation. Please could you send me the result of Sys.getenv("PATH"), this variable is use by the loader. 
Sincerely, 
Raphaël. 

----- Mail original -----

**Comment by ddmarathe** [comment]
ok, I will reset LIXOFT_HOME path as you suggested. But in response to another issue Marc had suggested to point the LIXOFT_HOME path to where lixoft.ini is located, that is why I tried that alternative when I was getting the error.

Here is the env. variable for PATH:

> Sys.getenv("PATH")
[1] "C:\\Program Files\\R\\R-3.1.2\\bin\\x64;C:\\PHSTMinGW\\bin;C:\\Program Files (x86)\\Pharsight\\Phoenix\\application\\lib\\NLME\\Executables\\;C:\\Program Files (x86)\\TIBCO\\splus81\\;C:\\Ora10g\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;\"C:\\Program Files (x86)\\Common Files\\EMC\";C:\\Program Files\\ActivIdentity\\ActivClient\\;C:\\Program Files (x86)\\ActivIdentity\\ActivClient\\;C:\\Program Files\\MATLAB\\R2012b\\bin;C:\\Program Files (x86)\\WebEx\\Productivity Tools;C:\\ProgramData\\Lixoft\\MlxLibrary1.1.1/tools/MinGW/bin"

**Comment by RaphaelKuate** [comment]
I see... you have another MinGW in your PATH, it may be the cause of conflicts with the MinGW of Lixoft, so could you remove C:\PHSTMinGW\bin from your PATH and try again? 

Raphaël. 

----- Mail original -----

**Comment by ddmarathe** [comment]
You are a genius!
I did not remove PHSTmin, but I appended the Mlxlibrary MinGW path so that it comes before MinGW in PHST (Phoenix s/w) and the error is gone and I am getting the output of simulation that I could verify with plotting function. Thanks much!
-----
Sys.setenv(
  PATH = paste(
    "C:\\ProgramData\\Lixoft\\MlxLibrary1.1.1\\tools\\MinGW\\bin", 
    Sys.getenv("PATH"), 
    sep = ";"
  )
)
-------

**Comment by ddmarathe** [comment]
Thank you for helping me towards troubleshooting and solving the problem, Raphael, Marc and Devin. I am closing the issue.
